### ISSUE TITLE
Investigate testing for components when using Karet

### ISSUE THREAD

**Issue by stuf** [stuf/masayards-calmm#6]
I think this probably breaks due to `karet` being used instead of `react`, when testing components with something like [`enzyme`](https://github.com/airbnb/enzyme), because using Observable-based components with `enzyme` with e.g. shallow rendering results in the familiar `Invariant Violation: Objects are not valid as a React child` error being thrown.

**Comment by polytypic** [comment]
Hmm... Could you provide a minimal example that produces this issue? In a previous project we did have tests using shallow rendering via `react-addons-test-utils`, though in that project we used `bacon.react.html` rather than `karet`, but I don't immediately see why things should work differently with `karet`.

**Comment by stuf** [comment]
Looked into how `enzyme` did its wrapping, which for its [Static Rendering API](https://github.com/airbnb/enzyme/blob/master/docs/api/render.md) just pipes the output of `renderToStaticMarkup` into `cheerio` for testing. Did an initial test of this in [`fleet.spec.js`](https://github.com/stuf/masayards-calmm/blob/master/test/modules/app-ui/fleet.spec.js#L26) which seems to work nicely.

**Comment by stuf** [comment]
@polytypic Actually, scrap that, I think I had made a mistake originally, which caused this error. Going to try to reproduce this when I get back at a computer.

**Comment by stuf** [comment]
Actually, this seems to have been something I missed on the initial round. Things Seem To Work(TM) now.
